HOC/Controllers/ApprovalsDashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HOC.Entities.Models.DB;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace HOC.Controllers
{
    public class ApprovalsDashboardController : Controller
    {
        private readonly HOCContext _context;

        public ApprovalsDashboardController(HOCContext context)
        {

            _context = context;
        }
        // GET: /<controller>/
        public IActionResult Index(string UserType, string UserId)
        {
            List<Projects> projects = new List<Projects>();
            projects = _context.Projects.Where(x =>
                x.Stage == Entities.Models.ProjectStage.Pending
                || x.Stage == Entities.Models.ProjectStage.Returned).ToList();

            return View(projects);
        }

        public IActionResult Process()
        {
            return View();
        }

        // GET: Dashboard/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var projects = await _context.Projects
                .Include(p => p.ApprovedByNavigation)
                .Include(p => p.CreatedByNavigation)
                .Include(p => p.ModifiedByNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (projects == null)
            {
                return NotFound();
            }

            return View(projects);
        }

        // POST: Dashboard/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var projects = await _context.Projects.FindAsync(id);
            _context.Projects.Remove(projects);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProjectsExists(int id)
        {
            return _context.Projects.Any(e => e.Id == id);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var projects = await _context.Projects
                .Include(p => p.ApprovedByNavigation)
                .Include(p => p.CreatedByNavigation)
                .Include(p => p.ModifiedByNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (projects == null)
            {
                return NotFound();
            }

            return View(projects);
        }

    }
}

HOC/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HOC.Entities.Models.DB;
using Microsoft.AspNetCore.Http;

namespace HOC.Controllers
{
    public class DashboardController : Controller
    {
        private readonly HOCContext _context;
        int currentUserID = 1;
        int CurrentUserRole = 1;
        int createdBy = 1;
        public DashboardController(HOCContext context)
        {
            _context = context;
        }

        public IActionResult Index(string UserType, string UserId, string UserEmail)
        {
            List<Projects> projects = new List<Projects>();
            
          
            if (UserEmail != null)
            {
                Users currentLoginUser = _context.Users.Where(x => x.UserName.Contains(UserEmail)).FirstOrDefault();

                if (currentLoginUser.Uid>0)
                {
                  
                    // set the key value in Cookie
                            CookieOptions option = new CookieOptions();
                        option.Expires = DateTime.Now.AddMinutes(10);
                        Response.Cookies.Append("currentLoginUser", currentLoginUser.Uid.ToString(), option);
                        currentUserID = currentLoginUser.Uid;
                    UserRoles currentLoginUserRole = _context.UserRoles.Where(x => x.UserId.Equals(currentLoginUser.Uid)).FirstOrDefault();
                    CurrentUserRole = currentLoginUserRole.RoleId;
                }
            }
            else if (Request.Cookies["currentLoginUser"] != null)
            {
                string userId = Request.Cookies["currentLoginUser"];
                currentUserID = Convert.ToInt16(userId);
                UserRoles currentLoginUserRole = _context.UserRoles.Where(x => x.UserId.Equals(currentUserID)).FirstOrDefault();
                CurrentUserRole = currentLoginUserRole.RoleId;
            }
            if (CurrentUserRole == 1)
            {
                projects = _context.Projects.Where(x => x.CreatedBy.Equals(currentUserID)).ToList();
            }
            else
            {
                projects = _context.Projects.ToList();
            }
            //if (UserType == "Organizer")
            //{
            //    projects = _context.Projects.ToList();
            //}
            //else
            //{
            //    projects = _context.Projects.ToList();
            //}
            return View(projects);
        }

        // GET: Dashboard/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var projects = await _context.Projects
                .Include(p => p.ApprovedByNavigation)
                .Include(p => p.CreatedByNavigation)
                .Include(p => p.ModifiedByNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (projects == null)
            {
                return NotFound();
            }

            return View(projects);
        }

        // GET: Dashboard/Create
        public IActionResult Create()
        {
            ViewData["ApprovedBy"] = new SelectList(_context.Users, "Uid", "UserName");
            ViewData["CreatedBy"] = new SelectList(_context.Users, "Uid", "UserName");
            ViewData["ModifiedBy"] = new SelectList(_context.Users, "Uid", "UserName");
            return View();
        }

        // POST: Dashboard/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Description,Approved,ApprovedOn,ApprovedBy,StartDate,EndDate,CreatedOn,CreatedBy,ModifiedOn,ModifiedBy,Stage")] Projects projects)
        {
            if (ModelState.IsValid)
            {
                if (Request.Cookies["currentLoginUser"] != null)
                {
                    string userId = Request.Cookies["currentLoginUser"];
                    currentUserID = Convert.ToInt16(userId);
                }
                projects.CreatedBy = currentUserID;


                projects.ApprovedOn = DateTime.Today;
                projects.CreatedOn = DateTime.Today;
                projects.ModifiedOn = DateTime.Today;
                projects.ApprovedBy = currentUserID;
                projects.ModifiedBy = currentUserID;
                projects.WorkflowId = 1;
                _context.Add(projects);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ApprovedBy"] = new SelectList(_context.Users, "Uid", "UserName", projects.ApprovedBy);
            ViewData["CreatedBy"] = new SelectList(_context.Users, "Uid", "UserName", projects.CreatedBy);
            ViewData["ModifiedBy"] = new SelectList(_context.Users, "Uid", "UserName", projects.ModifiedBy);
            return View(projects);
        }

        // GET: Dashboard/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var projects = await _context.Projects.FindAsync(id);
            createdBy = projects.CreatedBy;
            CookieOptions option = new CookieOptions();
            option.Expires = DateTime.Now.AddMinutes(10);
            Response.Cookies.Append("createdBy", createdBy.ToString(), option);
            
            if (projects == null)
            {
                return NotFound();
            }
            ViewData["ApprovedBy"] = new SelectList(_context.Users, "Uid", "UserName", projects.ApprovedBy);
            ViewData["CreatedBy"] = new SelectList(_context.Users, "Uid", "UserName", projects.CreatedBy);
            ViewData["ModifiedBy"] = new SelectList(_context.Users, "Uid", "UserName", projects.ModifiedBy);
            ViewData["Workflows"] = new SelectList(_context.Workflow, "Id", "Name", projects.WorkflowId);
            return View(projects);
        }

        // POST: Dashboard/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,Approved,ApprovedOn,ApprovedBy,StartDate,EndDate,ModifiedOn,ModifiedBy,Stage,WorkflowId")] Projects projects)
        {
            if (id != projects.Id)
            {
              
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    //projects.CreatedBy = currentUserID;

                    if (Request.Cookies["currentLoginUser"] != null)
                    {
                        string userId = Request.Cookies["currentLoginUser"];
                        currentUserID = Convert.ToInt16(userId);
                    }
                    if (Request.Cookies["createdBy"] != null)
                    {
                        string createdById = Request.Cookies["createdBy"];
                        createdBy = Convert.ToInt16(createdById);
                    }

                    projects.CreatedBy = createdBy;
                    projects.ApprovedOn = DateTime.Today;
                  projects.CreatedOn = DateTime.Today;
                    projects.ModifiedOn = DateTime.Today;
                    projects.ApprovedBy = currentUserID;
                    projects.ModifiedBy = currentUserID;
                    projects.Stage = Entities.Models.ProjectStage.Pending;
                    _context.Update(projects);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProjectsExists(projects.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ApprovedBy"] = new SelectList(_context.Users, "Uid", "UserName", projects.ApprovedBy);
            ViewData["CreatedBy"] = new SelectList(_context.Users, "Uid", "UserName", projects.CreatedBy);
            ViewData["ModifiedBy"] = new SelectList(_context.Users, "Uid", "UserName", projects.ModifiedBy);
            return View(projects);
        }

        // GET: Dashboard/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var projects = await _context.Projects
                .Include(p => p.ApprovedByNavigation)
                .Include(p => p.CreatedByNavigation)
                .Include(p => p.ModifiedByNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (projects == null)
            {
                return NotFound();
            }

            return View(projects);
        }

        // POST: Dashboard/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var projects = await _context.Projects.FindAsync(id);
            _context.Projects.Remove(projects);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProjectsExists(int id)
        {
            return _context.Projects.Any(e => e.Id == id);

HOC/Controllers/ScheculeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HOC.Entities.Models.DB;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace HOC.Controllers
{
    public class ScheduleController : Controller
    {
        private readonly HOCContext _context;

        public ScheduleController(HOCContext context)
        {
            _context = context;
        }
        // GET: /<controller>/
        public IActionResult Index(string UserType, string UserId)
        {
            List<Projects> projects = new List<Projects>();
            projects = _context.Projects.Where(x =>
                x.Stage == Entities.Models.ProjectStage.Approved).ToList();

            var data = projects.Select(x => 
                new Schedules{
                    Id = x.Id,
                    Name = x.Name,
                    Description = x.Description,
                    StartDate = x.StartDate,
                    EndDate = x.EndDate });

            return View(data);
        }

    }
}

HOC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- actual one for url ===== -->
    <meta name="google-site-verification" content="TOdaMaKGsy4k-MoFt3WJD9chXq1QtuIllzore2CBHkU" />
    <meta name="google-signin-client_id" content="190468735911-clsn8u4gkvqj68om0mtom56jir568tuq.apps.googleusercontent.com">
    <!-- paypal button code -->
    <script src="https://apis.google.com/js/platform.js" async defer></script>
    <link type="text/css" rel="stylesheet" href="~/css/Site.css" />
    <style>
        .navbar-inverse .navbar-nav > li > a { color: blue !important; font-size: 20px !important;        }
    </style>

    <title>@ViewData["Title"] - HOC</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link type="text/css" rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" style="height:125px;background-color: white">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a Style="color:#e2e5e6;font-family: Source Sans Pros, sans-serif;font-size:13px;padding: 10px 12px;border-right: 1px solid #dddddd66;" class="navbar-brand" href="@Url.Action("Index", "Home")">  <img style="width: 175px;" src="~/images/Logo.png" /></a>
                @*<a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">HOC</a>*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Dashboard" asp-action="Index">Projects</a></li>
                    <li><a asp-area="" asp-controller="ApprovalsDashboard" asp-action="Index">Pending Approvals</a></li>
                    <li><a asp-area="" asp-controller="Schedule" asp-action="Index">Scheduling Calendar</a></li>
                    @*<li><a asp-area="" asp-controller="ChatBox" asp-action="Index">ChatBox</a></li>*@
                </ul>
            </div>
            <div class="navbar-right" style="margin-top:8px;">
                <ul class="nav navbar-nav" style="margin: 14px 0px;">
                    <li style="line-height:30px;color:white;margin-right:20px;margin-left:35px">
                        <a style="display:inline" href="https://localhost:44390/Identity/Account/Login"><span> Logout</span></a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content" style="padding-top:90px">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - HOC</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>