HOC/Controllers/OrganizerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Web;
using HOC.Models;
using HOC.Entities.Models.DB;
using System.Net.Http;
using HOC.BusinessService;

namespace HOC.Controllers
{
    public class OrganizerController : Controller
    {

        private HOCContext context;

        public OrganizerController(HOCContext _context)

        {
            this.context = _context;

        }

        int GetUserID
        {
            get
            {
                int userId = 1;
                //userID = get it from user session

                return userId;
            }
        }


        // GET: Organizer
        public ActionResult Index()
        {
            return View();
        }

        // GET: Organizer/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Organizer/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Organizer/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        //public ActionResult Create(IFormCollection collection)
        public ActionResult Create(IFormCollection form)
        {
            Microsoft.Extensions.Primitives.StringValues val1, val2, val3, val4;
            try
            {

                // ModelState.AddModelError(string.Empty, "Server Error. Please contact administrator.");

                form.TryGetValue("ProjectName", out val1);
                form.TryGetValue("Description", out val2);
                form.TryGetValue("StartDate", out val3);
                form.TryGetValue("EndDate", out val4);

                Projects proj = new Projects();
                proj.Id = GetTempID;
                proj.CreatedBy = GetUserID;
                proj.Name = val1.ToString();
                proj.Description = val2.ToString();
                proj.StartDate = DateTime.Parse(val3.ToString());
                proj.EndDate = DateTime.Parse(val4.ToString()); ;
                proj.ApprovedOn = DateTime.Today;
                proj.CreatedOn = DateTime.Today;
                proj.ModifiedOn = DateTime.Today;
                proj.ApprovedBy = proj.CreatedBy;
                proj.ModifiedBy = proj.CreatedBy;
                this.context.Projects.Add(proj);
                this.context.SaveChanges();
                //proj. = 1;
                //HTTP POST
                //var postTask = client.PostAsJsonAsync<Project>("project", proj);


                // Campaign manager notification
                for (int i = 0; i < proj.WorkflowId; i++)
                {
                    var campaignManager = this.context.Workflow.Find(i++);
                    var emailInfo = new UserEmailInformation(campaignManager.Name, campaignManager.EmailAddress);
                    var messageInfo = new CampaignManagerNotificationEmail(proj.Name);
                    new EmailService(emailInfo, messageInfo);
                }
                //var result = postTask.Result;
                //if (result.IsSuccessStatusCode)
                //{
                return RedirectToAction("MyProjects");
                //}
                //}




            }
            catch (Exception ex)
            {
                return View();
            }
        }

        int GetTempID
        {
            get
            {
                DateTime now = DateTime.Now;
                string ids = now.Month.ToString() + now.Day.ToString() +
                    now.Hour.ToString() + now.Minute.ToString() + now.Second.ToString();

                return int.Parse(ids);
            }

        }

        // GET: Organizer/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Organizer/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Organizer/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Organizer/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public ActionResult ProjectDetails(int projId)
        {

            return View();
        }

        public IActionResult MyProjects()
        {
            List<Projects> projects = new List<Projects>();
                projects = this.context.Projects.ToList();

            
            return View(projects);
        }
    }
}

HOC/Views/Organizer/Create - Copy.cshtml
@model HOC.Models.cResearchProject
@{
    ViewData["Title"] = "Create a New Project";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<!--  jQuery -->
<script type="text/javascript" src="https://code.jquery.com/jquery-1.11.3.min.js"></script>

<!-- Isolated Version of Bootstrap, not needed if your site already uses Bootstrap -->
<link rel="stylesheet" href="https://formden.com/static/cdn/bootstrap-iso.css" />

<!-- Bootstrap Date-Picker Plugin -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css" />
<script src="~/js/Validate.js" type="text/javascript"></script>
<script>
    function Validate() {
        var projname = document.getElementById("ProjectName").value;

        //projname = trim(projname);
        if (projname == "") {
            alert("You must enter Project Name");
            return false;
        }
        
        var desc = document.getElementById("Description").value;

        if (desc == "") {
            alert("You must enter Description");
            return false;
        }

        var sdate = document.getElementById("StartDate").value;

        if (sdate == "") {
            alert("You must enter Start Date");
            return false;
        }

        var edate = document.getElementById("EndDate").value;

        if (edate == "") {
            alert("You must enter End Date");
            return false;
        }

        document.forms[0].submit();
        return true;
    }
</script>
<h2>Create a New Research Project</h2>
@using (Html.BeginForm("Create", "Organizer", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div id="divForm">
        <table id="tbContainer" style="width:100%">
            <tr>
                <td style="text-align:left; margin-left:20px">
                    <table class="datatable" style="border-width:3px">
                        <tr>
                            <td style="font-weight:bold;height:40px; padding-right:10px">Project Name: </td>
                            <td>
                                @Html.TextBox("ProjectName", "", new { @class = "regtext", @style = "width:400px" })
                                @Html.ValidationMessageFor(model => model.ProjectName)
                            </td>
                        </tr>
                        <tr>
                            <td style="font-weight:bold; padding-bottom:20px">Description: </td>
                            <td>
                                @Html.TextArea("Description", new { @style = "width:400px;height:150px" })
                            </td>
                        </tr>
                        <tr>
                            <td style="font-weight:bold; height:40px; ">Start Date: </td>
                            <td>
                                @Html.TextBox("StartDate", "", new { @class = "regtext", @style = "width:100px" })

                                <script type="text/javascript">
                                    $("#StartDate").datepicker();
                                </script>
                            </td>
                        </tr>
                        <tr>
                            <td style="font-weight:bold; height:40px;">End Date: </td>
                            <td>
                                @Html.TextBox("EndDate", "", new { @class = "regtext", @style = "width:100px" })
                                
                                <script type="text/javascript">
                                    $("#EndDate").datepicker();
                                </script>
                            </td>
                        </tr>
                        <tr>
                            <td></td>
                            <td style="height:60px;">
                                <button type="button" class="btn btn-primary" value="Save" onclick="javascript: return Validate();">Save</button>
                                <button type="button" class="btn btn-secondary">Cancel</button>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>

        </table>

    </div>
}

HOC/Views/Organizer/Create.cshtml
@model HOC.Models.cResearchProject
@{
    ViewData["Title"] = "Create a New Project";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<!--  jQuery -->
<script type="text/javascript" src="https://code.jquery.com/jquery-1.11.3.min.js"></script>

<!-- Isolated Version of Bootstrap, not needed if your site already uses Bootstrap -->
<link rel="stylesheet" href="https://formden.com/static/cdn/bootstrap-iso.css" />

<!-- Bootstrap Date-Picker Plugin -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css" />
<script src="~/js/Validate.js" type="text/javascript"></script>
<script>
    function Validate() {
        var projname = document.getElementById("ProjectName").value;

        //projname = trim(projname);
        if (projname == "") {
            alert("You must enter Project Name");
            return false;
        }
        
        var desc = document.getElementById("Description").value;

        if (desc == "") {
            alert("You must enter Description");
            return false;
        }

        var sdate = document.getElementById("StartDate").value;

        if (sdate == "") {
            alert("You must enter Start Date");
            return false;
        }

        var edate = document.getElementById("EndDate").value;

        if (edate == "") {
            alert("You must enter End Date");
            return false;
        }

        document.forms[0].submit();
        return true;
    }
</script>
<h2>Create a New Research Project</h2>
@using (Html.BeginForm("Create", "Organizer", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div id="divForm">
        <table id="tbContainer" style="width:100%">
            <tr>
                <td style="text-align:left; margin-left:20px">
                    <table class="datatable" style="border-width:3px">
                        <tr>
                            <td style="font-weight:bold;height:40px; padding-right:10px">Project Name: </td>
                            <td>
                                @Html.TextBox("ProjectName", "", new { @class = "regtext", @style = "width:400px" })
                                @Html.ValidationMessageFor(model => model.ProjectName)
                            </td>
                        </tr>
                        <tr>
                            <td style="font-weight:bold; padding-bottom:20px">Description: </td>
                            <td>
                                @Html.TextArea("Description", new { @style = "width:400px;height:150px" })
                            </td>
                        </tr>
                        <tr>
                            <td style="font-weight:bold; height:40px; ">Start Date: </td>
                            <td>
                                @Html.TextBox("StartDate", "", new { @class = "regtext", @style = "width:100px" })

                                <script type="text/javascript">
                                    $("#StartDate").datepicker();
                                </script>
                            </td>
                        </tr>
                        <tr>
                            <td style="font-weight:bold; height:40px;">End Date: </td>
                            <td>
                                @Html.TextBox("EndDate", "", new { @class = "regtext", @style = "width:100px" })
                                
                                <script type="text/javascript">
                                    $("#EndDate").datepicker();
                                </script>
                            </td>
                        </tr>
                        <tr>
                            <td></td>
                            <td style="height:60px;">
                                <button type="button" class="btn btn-primary" value="Save" onclick="javascript: return Validate();">Save</button>
                                <button type="button" class="btn btn-secondary">Cancel</button>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>

        </table>

    </div>
}

HOC/Views/Organizer/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

HOC/Views/Organizer/MyProjects.cshtml
@model IEnumerable<HOC.Entities.Models.DB.Projects>
@{
    ViewData["Title"] = "MyProjects";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>MyProjects</h2>

<table class="table">
    <thead>
        <tr>
            <th>
               Project Name
            </th>
            <th>
               Created By
            </th>
            <th>
               Date Created
            </th>
            <th>
               Proj Start Date
            </th>
            <th>
                Proj End Date
            </th>
            <th>
               Status
            </th>
            <th>
               Date Approved
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.Display(item.CreatedOn.ToString())
                </td>
                <td>
                    @Html.Display(item.CreatedOn.ToShortDateString())
                </td>
                <td>
                    @Html.Display(item.StartDate.ToShortDateString())
                </td>
                <td>
                    @Html.Display(item.EndDate.ToShortDateString())
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Stage)                   
                </td>
                <td>
                    @{
                        if (item.Stage == HOC.Entities.Models.ProjectStage.Approved)
                        {
                            Html.Display(item.ApprovedOn.ToShortDateString());
                                }
                    }
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>